#!/usr/bin/env python3
"""Generate requirements.txt từ pip freeze. Chạy sau pip install mới."""
import subprocess, sys

NEEDED = [
    "fastapi", "uvicorn", "python-multipart",
    "scikit-learn", "numpy", "pandas",
    "nltk", "langdetect",
    "beautifulsoup4", "requests", "aiofiles",
    "youtube-comment-downloader",
    "streamlit", "httpx",
]

result = subprocess.run(["pip", "freeze"], capture_output=True, text=True)
frozen = {}
for line in result.stdout.strip().split("\n"):
    if "==" in line:
        pkg = line.split("==")[0].lower().replace("-", "_")
        frozen[pkg] = line

lines = ["# Auto-generated by scripts/gen_requirements.py", "# DO NOT edit manually", ""]
missing = []
for pkg in NEEDED:
    key = pkg.lower().replace("-", "_")
    match = frozen.get(key) or next(
        (v for k, v in frozen.items() if pkg.lower().replace("-","") in k.replace("_","")), None
    )
    if match: lines.append(match)
    else: missing.append(pkg)

with open("requirements.txt", "w") as f:
    f.write("\n".join(lines) + "\n")

if missing:
    print(f"MISSING: {missing}", file=sys.stderr); sys.exit(1)
print(f"✅ {len(lines)-3} packages written to requirements.txt")
